/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    intMethod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_intMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_stringMethod
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
